server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/websiteBanDoCongNghe"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "IqD5dWsST/bP7RpDrB0x1mhr+nZdexZeOGrVnWWyw9q4MoomQ1zwm/z+qLAyCK4K"
  valid-duration: 3600
  refreshable-duration: 36000

file:
  upload-dir: src/main/resources/static/uploads

payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    returnUrl: "http://localhost:8080/payment/vn-pay-callback"
    tmnCode: "22556AE7"
    secretKey: ""
    version: 2.1.0
    command: "pay"
    orderType: "other"

outbound:
  identity:
    client-id: ""
    client-secret: ""
    redirect-uri: "http://localhost:3000/authenticate"
    grant-type: "authorization_code"